source 'https://rubygems.org'

gem 'jekyll', '~> 4.0'
gem 'kramdown', '= 2.1.0'
gem 'jemoji', '~> 0.11.1'
gem 'jekyll-paginate', '~> 1.1.0'
gem 'minitest', '~> 5.14.2'
gem 'listen', '~> 3.3'
gem 'rexml'
gem 'kramdown', '= 2.1.0'
gem 'webrick'
